#!/usr/bin/env python3
"""Tabulate lm_eval matrix outputs with server peak generation TPS."""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import re
import statistics
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple


LMEVAL_TS_RE = re.compile(r"^(\d{4}-\d{2}-\d{2}:\d{2}:\d{2}:\d{2})")
SERVER_TS_RE = re.compile(
    r"^\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\].*gen throughput \(token/s\): ([0-9]+(?:\.[0-9]+)?)"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--run-times",
        type=Path,
        nargs="+",
        required=True,
        help="One or more run_times.tsv files generated by mtp_lmeval_matrix_runner.py.",
    )
    parser.add_argument(
        "--server-log",
        type=Path,
        default=None,
        help="Default server log used when no prefix-specific mapping matches.",
    )
    parser.add_argument(
        "--server-log-by-prefix",
        action="append",
        default=[],
        help=(
            "Case-prefix server log mapping, e.g. "
            "--server-log-by-prefix conf_adapt_k8_t09=/path/server_k8.log"
        ),
    )
    parser.add_argument(
        "--output-tsv",
        type=Path,
        required=True,
        help="Output TSV path for reduced summary.",
    )
    parser.add_argument(
        "--output-markdown",
        type=Path,
        default=None,
        help="Optional markdown table output path with same reduced columns.",
    )
    parser.add_argument(
        "--sort-mode",
        choices=["strategy", "concurrency", "none"],
        default="strategy",
    )
    return parser.parse_args()


def parse_server_log_mapping(entries: Sequence[str]) -> List[Tuple[str, Path]]:
    mapping: List[Tuple[str, Path]] = []
    for entry in entries:
        if "=" not in entry:
            raise ValueError(f"Invalid --server-log-by-prefix entry: {entry!r}")
        prefix, path = entry.split("=", 1)
        prefix = prefix.strip()
        if not prefix:
            raise ValueError(f"Invalid prefix in --server-log-by-prefix: {entry!r}")
        mapping.append((prefix, Path(path.strip())))
    mapping.sort(key=lambda kv: len(kv[0]), reverse=True)
    return mapping


def choose_server_log(
    case_name: str,
    *,
    mapping: Sequence[Tuple[str, Path]],
    default_log: Optional[Path],
) -> Optional[Path]:
    for prefix, path in mapping:
        if case_name.startswith(prefix):
            return path
    return default_log


def parse_lmeval_timestamp(line: str) -> Optional[dt.datetime]:
    m = LMEVAL_TS_RE.match(line)
    if m is None:
        return None
    return dt.datetime.strptime(m.group(1), "%Y-%m-%d:%H:%M:%S")


def case_time_window(case_dir: Path) -> Tuple[Optional[dt.datetime], Optional[dt.datetime]]:
    log_path = case_dir / "lm_eval.log"
    if not log_path.exists():
        return None, None

    start: Optional[dt.datetime] = None
    end: Optional[dt.datetime] = None
    for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
        ts = parse_lmeval_timestamp(line)
        if ts is None:
            continue
        if start is None:
            start = ts
        end = ts
    return start, end


def parse_server_log(path: Path) -> List[Tuple[dt.datetime, float]]:
    points: List[Tuple[dt.datetime, float]] = []
    if not path.exists():
        return points
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = SERVER_TS_RE.match(line)
        if m is None:
            continue
        ts = dt.datetime.strptime(m.group(1), "%Y-%m-%d %H:%M:%S")
        tps = float(m.group(2))
        points.append((ts, tps))
    return points


def extract_server_stats(
    points: Sequence[Tuple[dt.datetime, float]],
    *,
    start: Optional[dt.datetime],
    end: Optional[dt.datetime],
) -> Tuple[Optional[float], Optional[float]]:
    values: List[float]
    if start is not None and end is not None and end >= start:
        values = [v for (ts, v) in points if start <= ts <= end]
        if len(values) == 0:
            values = [v for (_, v) in points]
    else:
        values = [v for (_, v) in points]

    if len(values) == 0:
        return None, None
    peak = max(values)
    if len(values) == 1:
        return peak, values[0]
    p95 = float(statistics.quantiles(values, n=20, method="inclusive")[18])
    return peak, p95


def find_latest_results_json(case_dir: Path) -> Optional[Path]:
    candidates = sorted(case_dir.rglob("results_*.json"), key=lambda p: p.stat().st_mtime)
    if not candidates:
        return None
    return candidates[-1]


def extract_eval_metrics(results_json: Path) -> Tuple[Optional[float], Optional[float]]:
    payload = json.loads(results_json.read_text(encoding="utf-8"))
    results = payload.get("results", {})
    task_block = results.get("gsm8k_cot_singleshot", {})
    strict = task_block.get("exact_match,strict-match")
    flex = task_block.get("exact_match,flexible-extract")
    strict_f = float(strict) if isinstance(strict, (int, float)) else None
    flex_f = float(flex) if isinstance(flex, (int, float)) else None
    return strict_f, flex_f


def infer_strat(case_name: str, family: str, k: int) -> str:
    m_non = re.fullmatch(r"non_mtp_c\d+", case_name)
    if m_non:
        return "non-MTP"
    m_k = re.fullmatch(r"mtp_k(\d+)_c\d+", case_name)
    if m_k:
        return f"k={int(m_k.group(1))}"
    m_conf = re.fullmatch(r"(conf_adapt_k\d+_t[0-9.]+)_c\d+", case_name)
    if m_conf:
        return m_conf.group(1)

    if family == "non_mtp":
        return "non-MTP"
    if family == "static":
        return f"k={k}"
    if family == "conf_adapt":
        m = re.search(r"(conf_adapt_k\d+_t[0-9.]+)", case_name)
        if m:
            return m.group(1)
        return f"conf_adapt_k{k}"
    return family


def read_run_times(path: Path) -> List[Tuple[str, int, str, int]]:
    rows: List[Tuple[str, int, str, int]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 4:
            continue
        case = parts[0].strip()
        c = int(parts[1].strip())
        family = parts[2].strip()
        k = int(parts[3].strip())
        rows.append((case, c, family, k))
    return rows


def format_num(value: Optional[float], decimals: int) -> str:
    if value is None:
        return ""
    return f"{value:.{decimals}f}"


def strategy_sort_key(strat: str) -> Tuple[int, str]:
    if strat.startswith("conf_adapt"):
        return (0, strat)
    if strat.startswith("k="):
        return (1, strat)
    if strat == "non-MTP":
        return (2, strat)
    return (3, strat)


def to_markdown(rows: Sequence[Dict[str, str]]) -> str:
    header = [
        "strat",
        "c",
        "case",
        "Server Peak Gen TPS",
        "Server Peak vs non-MTP",
        "Flex EM",
    ]
    lines = [
        "| " + " | ".join(header) + " |",
        "|---|---:|---|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    row["strat"],
                    row["c"],
                    row["case"],
                    row["Server Peak Gen TPS"],
                    row["Server Peak vs non-MTP"],
                    row["Flex EM"],
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    mapping = parse_server_log_mapping(args.server_log_by_prefix)
    default_server_log = args.server_log

    log_cache: Dict[Path, List[Tuple[dt.datetime, float]]] = {}
    rows: List[Dict[str, object]] = []

    for run_times in args.run_times:
        if not run_times.exists():
            raise FileNotFoundError(f"run_times file not found: {run_times}")
        root = run_times.parent
        for case_name, concurrency, family, k in read_run_times(run_times):
            case_dir = root / case_name
            if not case_dir.exists():
                print(f"[warn] missing case dir: {case_dir}", file=sys.stderr)
                continue

            server_log = choose_server_log(
                case_name=case_name,
                mapping=mapping,
                default_log=default_server_log,
            )

            if server_log is None:
                points: List[Tuple[dt.datetime, float]] = []
            else:
                resolved_log = server_log.resolve()
                if resolved_log not in log_cache:
                    log_cache[resolved_log] = parse_server_log(resolved_log)
                points = log_cache[resolved_log]

            start, end = case_time_window(case_dir)
            peak, _p95 = extract_server_stats(points, start=start, end=end)

            results_json = find_latest_results_json(case_dir)
            strict_em, flex_em = (None, None)
            if results_json is not None:
                strict_em, flex_em = extract_eval_metrics(results_json)
            else:
                print(f"[warn] no results_*.json in {case_dir}", file=sys.stderr)

            rows.append(
                {
                    "case": case_name,
                    "c": int(concurrency),
                    "family": family,
                    "k": int(k),
                    "strat": infer_strat(case_name=case_name, family=family, k=int(k)),
                    "server_peak": peak,
                    "strict_em": strict_em,
                    "flex_em": flex_em,
                }
            )

    non_mtp_peak_by_c: Dict[int, float] = {}
    for row in rows:
        if row["strat"] == "non-MTP" and isinstance(row["server_peak"], float):
            non_mtp_peak_by_c[int(row["c"])] = float(row["server_peak"])

    reduced_rows: List[Dict[str, str]] = []
    for row in rows:
        c = int(row["c"])
        peak = row["server_peak"]
        base_peak = non_mtp_peak_by_c.get(c)
        rel = None
        if isinstance(peak, float) and isinstance(base_peak, float) and base_peak > 0:
            rel = peak / base_peak
        reduced_rows.append(
            {
                "strat": str(row["strat"]),
                "c": str(c),
                "case": str(row["case"]),
                "Server Peak Gen TPS": format_num(peak if isinstance(peak, float) else None, 2),
                "Server Peak vs non-MTP": format_num(rel, 3),
                "Flex EM": format_num(
                    row["flex_em"] if isinstance(row["flex_em"], float) else None, 4
                ),
            }
        )

    if args.sort_mode == "strategy":
        reduced_rows.sort(
            key=lambda r: (strategy_sort_key(r["strat"]), int(r["c"]), r["case"])
        )
    elif args.sort_mode == "concurrency":
        reduced_rows.sort(
            key=lambda r: (int(r["c"]), strategy_sort_key(r["strat"]), r["case"])
        )

    args.output_tsv.parent.mkdir(parents=True, exist_ok=True)
    with args.output_tsv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "strat",
                "c",
                "case",
                "Server Peak Gen TPS",
                "Server Peak vs non-MTP",
                "Flex EM",
            ],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(reduced_rows)

    if args.output_markdown is not None:
        args.output_markdown.parent.mkdir(parents=True, exist_ok=True)
        args.output_markdown.write_text(to_markdown(reduced_rows), encoding="utf-8")

    print(f"Wrote reduced TSV: {args.output_tsv}")
    if args.output_markdown is not None:
        print(f"Wrote markdown table: {args.output_markdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
